name: .NET

on:
  workflow_dispatch:
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TAF_EasyRest
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.8
    - name: Build
      run: dotnet build --no-restore TAF_EasyRest
    - name: Test
      run: dotnet test --no-build --verbosity normal TAF_EasyRest
