name: Tests_on_Linux

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release TAF_EasyRest    
      
    - name: Test with X client
      run: dotnet test --configuration Release TAF_EasyRest
