name: Tests_on_Linux

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TAF_EasyRest
    - name: Build
      run: dotnet build --no-restore TAF_EasyRest
    - name: Setup X client
      run: xvfb-run --auto-servernum
    - name: Test
      run: dotnet test --no-build --verbosity normal TAF_EasyRest
